[project]
name = "crew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chardet>=5.2.0",
    "chromadb>=1.0.13",
    "crewai>=0.130.0",
    "crewai-tools>=0.0.1",
    "sentence-transformers>=4.1.0",
    "streamlit>=1.46.0",
]
